name: queen_vs_pawn_winning_zone
description: "Test yourself in the chess Queen vs Pawn endgame winning zone."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  slang: ^4.1.0
  slang_flutter: ^4.1.0
  flutter_localizations:
    sdk: flutter
  simple_chess_board: ^1.5.0
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  slang_build_runner: ^4.1.0

flutter:
  uses-material-design: true
